### ISSUE TITLE
1.5.2 compatibility

### ISSUE THREAD

**Issue by Kidzukami** [ahuyn/anomaly-exo#5]
Will this addon and "anomaly loot" be compatible with 1.5.2 in the future?

**Comment by ahuyn** [comment]
What incompatibilities exist with 1.5.2?

**Comment by Kidzukami** [comment]
[xray_kidzu.log](https://github.com/ahuyn/anomaly-exo/files/9333191/xray_kidzu.log)

**Comment by ahuyn** [comment]
Please download from release tab in the future: https://github.com/ahuyn/anomaly-exo/releases/tag/latest
